const words = [
    "Cyberware", "Netrunning", "Datajack", "Cyberspace", "Virtual Reality","VR", 
    "Augmented Reality", "AR", "Hacking", "Decking", "Cyberdeck", "Intrusion","Countermeasures","Electronics", 
    "Black ICE", "Firewall", "Mesh Network", "Ghosting", "Cybercrime", "Cyberpunk", "Mega Corporation", 
    "Dystopia", "Street Samurai", "Hacker Collective", "Neuromancer", "Brain-Computer", 
    "Neural Implant", "Cyberpsychosis", "Transhumanism", "Techno-Dystopia", "Synthetics", "Nanotechnology", 
    "Biopunk", "Posthuman", "Body Modification", "Simstim", "Transgenderism", "Cybernetics", "Autonomous Vehicles", 
    "Virtual Currency", "Cryptocurrency", "Darknet", "Infovore", "Techno-Organic", "Genetic Engineering", 
    "Brain Hacking", "Corporate Espionage", "Surveillance State", "Neural Interface", "Brain Implant", "Mind Control", 
    "Street Doc", "Body Augmentation", "Corporate Domination", "Cybernetic Enhancement", "Transhuman", 
    "Digital Identity Theft", "Corporate Warfare", "Information Broker", "Memory Implant", "Virtual Addiction", 
    "Brainwashing", "Technological Singularity", "Techno-Utopia", "Cyber War", "Technological Surveillance", 
    "Hacktivism", "Reality Hacking", "Genetic Modification", "Mind Uploading", "Cybernetic Rebellion", 
    "Shadow Government", "Cybernetic Organism (Cyborg)", "Technological Totalitarianism", "Brain-to-Brain Interface", 
    "Memory Extraction", "Digital Democracy", "Technological Liberation", "Neuroplasticity", "Techno-Anarchy", 
    "Memory Erasure", "Reality Manipulation", "Technological Determinism", "Mind-Machine Interface", "Interface", "Robotics",
    "Artificial Intelligence", "AI",
    "Automation",
    "Machine Learning",
    "Human-Robot Interaction",
    "Robot Vision",
    "Industrial Robotics",
    "Collaborative Robots",
    "Autonomous Robots",
    "Control Systems",
    "Kinematics",
    "Dynamics",
    "End Effector",
    "Manipulator",
    "Gripper",
    "Actuator",
    "Sensor Fusion",
    "Perception",
    "Locomotion",
    "Navigation",
    "Localization",
    "Mapping",
    "Path Planning",
    "Simultaneous", "Localization", "Mapping",
    "Telerobotics",
    "Teleoperation",
    "Robotic Arm",
    "Mobile Robot",
    "Unmanned Aerial Vehicle", "UAV",
    "Unmanned Ground Vehicle",
    "Unmanned Underwater Vehicle",
    "Exoskeleton",
    "Swarm Robotics",
    "Multi-Robot Systems",
    "Robotic Surgery",
    "Rehabilitation Robotics",
    "Surgical Robotics",
    "Medical Robotics",
    "Service Robots",
    "Domestic Robots",
    "Social Robots",
    "Entertainment Robotics",
    "Educational Robotics",
    "Agricultural Robotics",
    "Construction Robotics",
    "Inspection Robots",
    "Maintenance Robots",
    "Cleaning Robots",
    "Delivery Robots",
    "Warehouse Robots",
    "Logistics Robots",
    "Inspection Robots",
    "Surveillance Robots",
    "Underwater Robotics",
    "Space Robotics",
    "Mars Rovers",
    "Lunar Rovers",
    "Remote Sensing",
    "Robot", "Operating", "System",
    "Open Robotics",
    "Robot Ethics",
    "Robotic Laws",
    "Safety Standards",
    "Robotic Simulation",
    "Robotic Programming",
    "Human-Robot Collaboration",
    "Robotic Manipulation",
    "Robotic Grasping",
    "Telepresence",
    "Teleoperation",
    "Augmented Reality",
    "Remote Monitoring",
    "Robotics Research",
    "Roboticists",
    "Robotics Engineering",
    "Robotic Platforms",
    "ROS Packages",
    "Frameworks",
    "Simulation Environments",
    "Design",
    "Prototyping",
    "Manufacturing",
    "Components",
    "Integration",
    "Sensors",
    "Actuators",
    "Batteries",
    "Controllers",
    "Software",
    "Hardware",
    "Power Systems",
    "Communication Systems",
    "Networks",
    "APIs",
    "Calibration",
    "Testing",
    "Validation",
    "Deployment",
    "Maintenance",
    "Upgrades","Space Exploration",
    "Astronaut",
    "Rocket",
    "Spacecraft",
    "Satellite",
    "Space Station",
    "International Space Station (ISS)",
    "Space Shuttle",
    "Space Mission",
    "Lunar Mission",
    "Mars Mission",
    "Planetary Exploration",
    "Interplanetary Travel",
    "Interstellar Travel",
    "Space Tourism",
    "Spacewalk", "EVA", "Extravehicular", "Activity",
    "Orbital Mechanics",
    "Space Propulsion",
    "Rocket Engine",
    "Thrust",
    "Orbital Insertion",
    "Reentry",
    "Atmospheric Entry",
    "Space Weather",
    "Space Debris",
    "Space Junk",
    "Space Agency",
    "Wetware",
    "Commercial Spaceflight",
    "Spaceport",
    "Launch Pad",
    "Payload",
    "Launch Vehicle",
    "Space Launch System (SLS)",
    "Falcon Heavy",
    "Soyuz Rocket",
    "Delta IV",
    "Communication Satellite",
    "Weather Satellite",
    "Earth Observation Satellite",
    "Remote Sensing Satellite",
    "Navigation Satellite",
    "Geostationary",
    "Polar Orbit",
    "Mars",
    "Lunar",
    "Probe",
    "New Horizons",
    "Observatory",
    "Space Science",
    "Astrophysics",
    "Planetary Science",
    "Astrobiology",
    "Exoplanet",
    "Space Colonization",
    "Lunar Base",
    "Mars Colony",
    "Space Habitats",
    "Space Mining",
    "Asteroid Mining",
    "Space Resources",
    "Lunar Resources",
    "Mars Resources",
    "Space Manufacturing",
    "In-Situ", "Resource", "Utilization",
    "Space Elevator",
    "Lunar Gateway",
    "Artemis Program",
    "Mars Sample Return",
    "Lunar Exploration Program",
    "Space Law",
    "Outer Space Treaty",
    "Space Policy",
    "Space Advocacy",
    "Space Education",
    "Space Industry",
    "Space Technology",
    "Space Medicine",
    "Microgravity Research",
    "Space Agriculture",
    "Space Food",
    "Space Suit",
    "Life Support Systems",
    "Space Radiation",
    "Space Weathering",
    "Space Biology",
    "Space Chemistry",
    "Space Physics",
    "Space Engineering","Weyland-Yutani Corporation",
    "Cyber",
    "Dynamics",
    "Dyne",
    "Yutani",
    "Wayland",
    "Gen", "Corporation",
    "Galactic",
    "Blaster",
    "Hyperdrive",
    "Lightspeed"
    "Force Field",
    "Droid Army",
    "Galactic Credits",
    "Spice Trade",
    "Bacta Tank",
    "Holocron",
    "Hologram", "Communication",
    "Carbonite Freezing",
    "Lightsaber Crystal",
    "Mandalorian Armor",
    "Death Star Plans",
    "Sith Holocron",
    "Jedi Holocron",
    "Starship Engineering",
    "BlasTech Industries",
    "Sienar Fleet Systems",
    "Kuat Drive Yards",
    "Arakyd Industries",
    "Corellian Engineering Corporation",
    "Wookiee Bowcaster",
    "Zygerrian Slave Empire",
    "Kaminoan Cloning Facilities",
    "Mos Eisley Cantina",
    "Dagobah Swamp",
    "Cloud City",
    "Tatooine Sandcrawler",
    "Ewok Village",
    "Gungan City",
    "Sith Temple",
    "Jedi Temple",
    "Naboo Royal Palace",
    "Coruscant Underworld",
    "Geonosian Hive",
    "Utapau Sinkhole",
    "Bespin Gas Mines",
    "Kashyyyk Treehouses",
    "Mustafar Lava Fields",
    "Tatooine Moisture Farm",
    "Endor Forest Moon",
    "Hoth Ice Caves",
    "Dantooine Ruins",
    "Alderaan Palace",
    "Naboo Lake Country",
    "Jakku Junkyard",
    "Scarif Beaches",
    "Exegol Sith Citadel",
    "Hosnian Prime Government District",
    "Mon Cala Underwater Cities",
    "Nar Shaddaa Smuggler's Moon",
    "Canto Bight Casino City",
    "Felucia Fungus Forests","Aerospace Engineering",
    "Astronautics",
    "Rocket Science",
    "Orbital Mechanics",
    "Propulsion Systems",
    "Spacecraft Design",
    "Structural Engineering",
    "Materials Science",
    "Robotics Engineering",
    "Artificial Gravity",
    "Life Support Systems",
    "Space Habitat Design",
    "Space Suit Engineering",
    "Environmental Control Systems",
    "Thermal Management Systems",
    "Power Generation Systems",
    "Communication Systems",
    "Navigation Systems",
    "Launch Vehicle Design",
    "Interplanetary Travel",
    "Planetary Landing Systems",
    "Lunar Base Construction",
    "Martian Colony Establishment",
    "Terraforming Technologies",
    "Habitat Agriculture Systems",
    "Water Extraction Technologies",
    "Mining and Resource Extraction",
    "In-Situ Resource Utilization (ISRU)",
    "3D Printing in Space",
    "Space Elevator Design",
    "Orbital Space Stations",
    "Interstellar Travel Concepts",
    "Generation Ships",
    "Space Colony Architecture",
    "Biodome Design",
    "Atmospheric Processing",
    "Radiation Shielding",
    "Artificial Lighting Systems",
    "Hydroponic Farming Systems",
    "Waste Recycling Systems",
    "Telecommunications Infrastructure",
    "Deep Space Communication Networks",
    "Satellite Constellations",
    "Lunar Mining Operations",
    "Martian Resource Utilization",
    "Asteroid Mining Techniques",
    "Solar Power Satellites",
    "Nuclear Propulsion Systems",
    "Ion Thrusters",
    "Fusion Reactor Development",
    "Magnetic Shielding",
    "Algae-Based Life Support Systems",
    "Inflatable Habitat Modules",
    "Space Tourism Infrastructure",
    "Orbital Debris Mitigation",
    "Space Weather Monitoring",
    "Space Traffic Management",
    "Space Law and Regulations",
    "Space Colonization Ethics",
    "Genetic Engineering for Space Adaptation",
    "Cognitive Psychology in Space",
    "Artificial Intelligence in Space Exploration",
    "Crew Training Facilities",
    "Space Simulators",
    "Remote Sensing Technologies",
    "Geospatial Mapping Systems",
    "Exoplanet Exploration Tools",
    "Terraforming Simulation Models",
    "Space Policy Analysis",
    "Space Settlement Planning",
    "Space Tourism Marketing",
    "Space Entertainment Industry",
    "Space Colonization Advocacy",
    "Orbital Debris Cleanup Technologies",
    "Deep Space Telescopes",
    "Quantum Communication Systems",
    "Lunar Base Construction Robots",
    "Martian Rover Technologies",
    "Lunar and Martian Agriculture Research",
    "Space Weather Prediction Models",
    "Space Elevator Tether Materials",
    "Lunar and Martian Water Extraction Vehicles",
    "Deep Space Habitat Modules",
    "Space Mining Automation Systems",
    "Space Manufacturing Techniques",
    "Bioregenerative Life Support Systems",
    "Space-Based Medical Research Facilities",
    "3D Printed Lunar and Martian Habitats",
    "Lunar and Martian Transportation Systems",
    "Space Colonization Finance Models",
    "Orbital Manufacturing Facilities",
    "Space Elevator Anchor Points",
    "Orbital Hotels and Resorts",
    "Lunar and Martian Construction Materials",
    "Space Food Production Methods",
    "Lunar and Martian In-Situ Fabrication",
    "Space Tourism Experience Design",
    "Space Colonization Educational Initiatives",
    "Lunar and Martian Colony Governance",
    "Space Colonization Sustainability Studies"
];

const generateName = () => {
    const selectedIndices = [];
    while (selectedIndices.length < 3) {
        const randomIndex = Math.floor(Math.random() * words.length);
        if (!selectedIndices.includes(randomIndex)) {
            selectedIndices.push(randomIndex);
        }
    }

    const name = words[selectedIndices[0]] + " " + words[selectedIndices[1]] + " " + words[selectedIndices[2]];
    document.getElementById("nameContainer").innerText = name;
};

document.getElementById("generateBtn").addEventListener("click", generateName);

